---
title: "Stewardship for `r s`"
author: "Lead Steward: `r first(SiteAll$Lead_Steward)`"
date: "`r Sys.Date()`"
output: pdf_document
classoption: landscape, a3paper
---

```{r setup, include=FALSE}
library(knitr)
library(tidyverse)
library(flextable)
options(knitr.kable.NA = '', knitr.table.format = "latex")
library(kableExtra)
library(gt)
#library(array)
#library(booktabs)
#library(threeparttablex)
opts_chunk$set(echo = TRUE)

# text to reinsert in title: SiteB$Site[1]

# Instructions here for producing multiple PDFs: https://stackoverflow.com/questions/30422008/r-knitr-pdf-is-there-a-posssibility-to-automatically-save-pdf-reports-generate

```

## Boundary Issues


```{r boundary, echo=FALSE}
#Report by Site
SiteB_table <- SiteB %>%
  rename(Treatment = Treat_Desc,
         Description = Issue_Desc) %>%
  filter(!is.na(Site)) %>%
  select(1,3:(length(SiteB)-2)) %>%
  discard(~all(is.na(.) | . == "")) %>%
  mutate(across(everything(), ~gsub(pattern = "_", replacement = "", .)),
         across(everything(), ~gsub(pattern = "&", replacement = "and", .)),
         across(everything(), ~gsub(pattern = "%", replacement = " pct", .)),
         across(everything(), ~gsub(pattern = "#", replacement = "", .)))
  
#Create table
if(nrow(SiteB_table) > 0){
  kbl(SiteB_table, row.names = F, escape = F, booktabs = T) %>%
    column_spec(3:4, width = "3in") %>%
    kable_styling(font_size = 8, latex_options = c("striped", "hover"),
                  position = "left")}

#gt(SiteB_table)
```

## Channel Issues

```{r channel, echo=FALSE}
SiteC_table <- SiteC %>%
  rename(Description = Issue_Desc,
         Treatment = Treat_Desc) %>%
  filter(!is.na(Site)) %>%
  select(1,3:(length(SiteC)-2)) %>%
  discard(~all(is.na(.) | . == "")) %>%
  mutate(across(everything(), ~gsub(pattern = "_", replacement = "", .)),
         across(everything(), ~gsub(pattern = "&", replacement = "and", .)),
         across(everything(), ~gsub(pattern = "%", replacement = " pct", .)),
         across(everything(), ~gsub(pattern = "#", replacement = "", .)))

if(nrow(SiteC_table) > 0){
  kbl(SiteC_table, row.names = F, escape = F, booktabs = T) %>%
    column_spec(5, width = "3in") %>%
    kable_styling(font_size = 8, latex_options = "striped",
                  position = "left")}
```

\newpage

## Vegetation Issues

```{r vegetation, echo=FALSE}
SiteV_table <- SiteV %>%
  rename(Description = Issue_Desc,
         Treatment = Treat_Desc,
         Method = Treat_Method_1) %>%
  filter(!is.na(Site)) %>%
  select(1,3:(length(SiteV)-2)) %>%
  discard(~all(is.na(.) | . == "")) %>%
  mutate(across(everything(), ~gsub(pattern = "_", replacement = "", .)),
         across(everything(), ~gsub(pattern = "&", replacement = "and", .)),
         across(everything(), ~gsub(pattern = "%", replacement = " pct", .)),
         across(everything(), ~gsub(pattern = "#", replacement = "", .)))

if(nrow(SiteV_table) > 0){
  kbl(SiteV_table, row.names = F, escape = F, booktabs = T) %>%
  column_spec(4, width = "3in") %>%
  kable_styling(font_size = 8, latex_options = "striped",
                position = "left")}
```



## Weed Issues

```{r weeds, echo=FALSE}
SiteW_table <- SiteW %>%
  rename(Species1 = InvSpecies_1, 
         Species2 = InvSpecies_2, 
         Issue = Issue_Desc,
         Treatment = Treat_Desc,
         Method = Treat_Method_1) %>%
  filter(!is.na(Site)) %>%
  select(1,3:(length(SiteW)-2)) %>%
  discard(~all(is.na(.) | . == "")) %>%
  mutate(across(everything(), ~gsub(pattern = "_", replacement = "", .)),
         across(everything(), ~gsub(pattern = "&", replacement = "and", .)),
         across(everything(), ~gsub(pattern = "%", replacement = " pct", .)),
         across(everything(), ~gsub(pattern = "#", replacement = "", .)))


if(nrow(SiteW_table) > 0){
  kbl(SiteW_table, row.names = F, escape = F, booktabs = T) %>%
    column_spec(4:5, width = "2in") %>%
    kable_styling(font_size = 8, latex_options = "striped",
                  position = "left")}
```


## Miscellaneous Issues

```{r misc, echo=FALSE}
SiteM_table <- SiteM %>%
  rename(Treatment = Treat_Desc,
         Description = Issue_Desc,
         LocationOrFeature = Issue_LocationOrFeature) %>%
  filter(!is.na(Site)) %>%
  select(1,3:(length(SiteM)-2)) %>%
  discard(~all(is.na(.) | . == "")) %>%
  mutate(across(everything(), ~gsub(pattern = "_", replacement = "", .)),
         across(everything(), ~gsub(pattern = "&", replacement = "and", .)),
         across(everything(), ~gsub(pattern = "%", replacement = " pct", .)),
         across(everything(), ~gsub(pattern = "#", replacement = "", .)))

if(nrow(SiteM_table) > 0){
  kbl(SiteM_table, row.names = F, escape = F, booktabs = T) %>%
  column_spec(4:5, width = "2in") %>%
  kable_styling(font_size = 8, latex_options = "striped",
                position = "left")
}

```


